output_dir: ~/DATA/zeus/hnguyent/projects/LEARNING/ULTRA/output

dataset:
  class: {{ dataset }}
  root: ~/DATA/zeus/hnguyent/projects/LEARNING/ULTRA/kg-datasets/
  version: {{ version }}

model:
  class: Ultra
  relation_model:
    class: NBFNet
    input_dim: 64
    hidden_dims: [64, 64, 64, 64, 64, 64]
    message_func: distmult
    aggregate_func: sum
    short_cut: yes
    layer_norm: yes
  entity_model:
    class: IndNBFNet
    input_dim: 64
    hidden_dims: [64, 64, 64, 64, 64, 64]
    message_func: distmult
    aggregate_func: sum
    short_cut: yes
    layer_norm: yes

task:
  name: InductiveInference
  num_negative: 256
  strict_negative: yes
  adversarial_temperature: 1
  metric: [mr, mrr, hits@1, hits@3, hits@10, hits@10_50]

optimizer:
  class: AdamW
  lr: 5.0e-4

train:
  gpus: {{ gpus }}
  batch_size: 16
  num_epoch: {{ epochs }}
  log_interval: 100
  batch_per_epoch: {{ bpe }}
  #logger: wandb

checkpoint: {{ ckpt }}